/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ys.liferay.cert.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.ys.liferay.cert.service.persistence.InventoryPK;

import java.io.Serializable;

/**
 * The base model interface for the Inventory service. Represents a row in the &quot;LCert_Inventory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ys.liferay.cert.model.impl.InventoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ys.liferay.cert.model.impl.InventoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Inventory
 * @see com.ys.liferay.cert.model.impl.InventoryImpl
 * @see com.ys.liferay.cert.model.impl.InventoryModelImpl
 * @generated
 */
public interface InventoryModel extends BaseModel<Inventory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a inventory model instance should use the {@link Inventory} interface instead.
	 */

	/**
	 * Returns the primary key of this inventory.
	 *
	 * @return the primary key of this inventory
	 */
	public InventoryPK getPrimaryKey();

	/**
	 * Sets the primary key of this inventory.
	 *
	 * @param primaryKey the primary key of this inventory
	 */
	public void setPrimaryKey(InventoryPK primaryKey);

	/**
	 * Returns the product ID of this inventory.
	 *
	 * @return the product ID of this inventory
	 */
	public long getProductId();

	/**
	 * Sets the product ID of this inventory.
	 *
	 * @param productId the product ID of this inventory
	 */
	public void setProductId(long productId);

	/**
	 * Returns the product name of this inventory.
	 *
	 * @return the product name of this inventory
	 */
	@AutoEscape
	public String getProductName();

	/**
	 * Sets the product name of this inventory.
	 *
	 * @param productName the product name of this inventory
	 */
	public void setProductName(String productName);

	/**
	 * Returns the product code of this inventory.
	 *
	 * @return the product code of this inventory
	 */
	public long getProductCode();

	/**
	 * Sets the product code of this inventory.
	 *
	 * @param productCode the product code of this inventory
	 */
	public void setProductCode(long productCode);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Inventory inventory);

	public int hashCode();

	public CacheModel<Inventory> toCacheModel();

	public Inventory toEscapedModel();

	public Inventory toUnescapedModel();

	public String toString();

	public String toXmlString();
}