/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ys.cert.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import com.ys.cert.model.Truck;
import com.ys.cert.service.CarsLocalService;
import com.ys.cert.service.CarsService;
import com.ys.cert.service.TruckLocalService;
import com.ys.cert.service.persistence.CarsPersistence;
import com.ys.cert.service.persistence.TruckPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the truck local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.ys.cert.service.impl.TruckLocalServiceImpl}.
 * </p>
 *
 * @author AC70602
 * @see com.ys.cert.service.impl.TruckLocalServiceImpl
 * @see com.ys.cert.service.TruckLocalServiceUtil
 * @generated
 */
public abstract class TruckLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements TruckLocalService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.ys.cert.service.TruckLocalServiceUtil} to access the truck local service.
	 */

	/**
	 * Adds the truck to the database. Also notifies the appropriate model listeners.
	 *
	 * @param truck the truck
	 * @return the truck that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Truck addTruck(Truck truck) throws SystemException {
		truck.setNew(true);

		return truckPersistence.update(truck, false);
	}

	/**
	 * Creates a new truck with the primary key. Does not add the truck to the database.
	 *
	 * @param truckId the primary key for the new truck
	 * @return the new truck
	 */
	public Truck createTruck(long truckId) {
		return truckPersistence.create(truckId);
	}

	/**
	 * Deletes the truck with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param truckId the primary key of the truck
	 * @return the truck that was removed
	 * @throws PortalException if a truck with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public Truck deleteTruck(long truckId)
		throws PortalException, SystemException {
		return truckPersistence.remove(truckId);
	}

	/**
	 * Deletes the truck from the database. Also notifies the appropriate model listeners.
	 *
	 * @param truck the truck
	 * @return the truck that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public Truck deleteTruck(Truck truck) throws SystemException {
		return truckPersistence.remove(truck);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Truck.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return truckPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return truckPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return truckPersistence.findWithDynamicQuery(dynamicQuery, start, end,
			orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return truckPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public Truck fetchTruck(long truckId) throws SystemException {
		return truckPersistence.fetchByPrimaryKey(truckId);
	}

	/**
	 * Returns the truck with the primary key.
	 *
	 * @param truckId the primary key of the truck
	 * @return the truck
	 * @throws PortalException if a truck with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public Truck getTruck(long truckId) throws PortalException, SystemException {
		return truckPersistence.findByPrimaryKey(truckId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return truckPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the trucks.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of trucks
	 * @param end the upper bound of the range of trucks (not inclusive)
	 * @return the range of trucks
	 * @throws SystemException if a system exception occurred
	 */
	public List<Truck> getTrucks(int start, int end) throws SystemException {
		return truckPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of trucks.
	 *
	 * @return the number of trucks
	 * @throws SystemException if a system exception occurred
	 */
	public int getTrucksCount() throws SystemException {
		return truckPersistence.countAll();
	}

	/**
	 * Updates the truck in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param truck the truck
	 * @return the truck that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Truck updateTruck(Truck truck) throws SystemException {
		return updateTruck(truck, true);
	}

	/**
	 * Updates the truck in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param truck the truck
	 * @param merge whether to merge the truck with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the truck that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public Truck updateTruck(Truck truck, boolean merge)
		throws SystemException {
		truck.setNew(false);

		return truckPersistence.update(truck, merge);
	}

	/**
	 * Returns the cars local service.
	 *
	 * @return the cars local service
	 */
	public CarsLocalService getCarsLocalService() {
		return carsLocalService;
	}

	/**
	 * Sets the cars local service.
	 *
	 * @param carsLocalService the cars local service
	 */
	public void setCarsLocalService(CarsLocalService carsLocalService) {
		this.carsLocalService = carsLocalService;
	}

	/**
	 * Returns the cars remote service.
	 *
	 * @return the cars remote service
	 */
	public CarsService getCarsService() {
		return carsService;
	}

	/**
	 * Sets the cars remote service.
	 *
	 * @param carsService the cars remote service
	 */
	public void setCarsService(CarsService carsService) {
		this.carsService = carsService;
	}

	/**
	 * Returns the cars persistence.
	 *
	 * @return the cars persistence
	 */
	public CarsPersistence getCarsPersistence() {
		return carsPersistence;
	}

	/**
	 * Sets the cars persistence.
	 *
	 * @param carsPersistence the cars persistence
	 */
	public void setCarsPersistence(CarsPersistence carsPersistence) {
		this.carsPersistence = carsPersistence;
	}

	/**
	 * Returns the truck local service.
	 *
	 * @return the truck local service
	 */
	public TruckLocalService getTruckLocalService() {
		return truckLocalService;
	}

	/**
	 * Sets the truck local service.
	 *
	 * @param truckLocalService the truck local service
	 */
	public void setTruckLocalService(TruckLocalService truckLocalService) {
		this.truckLocalService = truckLocalService;
	}

	/**
	 * Returns the truck persistence.
	 *
	 * @return the truck persistence
	 */
	public TruckPersistence getTruckPersistence() {
		return truckPersistence;
	}

	/**
	 * Sets the truck persistence.
	 *
	 * @param truckPersistence the truck persistence
	 */
	public void setTruckPersistence(TruckPersistence truckPersistence) {
		this.truckPersistence = truckPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();

		PersistedModelLocalServiceRegistryUtil.register("com.ys.cert.model.Truck",
			truckLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.ys.cert.model.Truck");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Truck.class;
	}

	protected String getModelClassName() {
		return Truck.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = truckPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = CarsLocalService.class)
	protected CarsLocalService carsLocalService;
	@BeanReference(type = CarsService.class)
	protected CarsService carsService;
	@BeanReference(type = CarsPersistence.class)
	protected CarsPersistence carsPersistence;
	@BeanReference(type = TruckLocalService.class)
	protected TruckLocalService truckLocalService;
	@BeanReference(type = TruckPersistence.class)
	protected TruckPersistence truckPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private TruckLocalServiceClpInvoker _clpInvoker = new TruckLocalServiceClpInvoker();
}