/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ys.cert.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Cars service. Represents a row in the &quot;Vehicle_Cars&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ys.cert.model.impl.CarsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ys.cert.model.impl.CarsImpl}.
 * </p>
 *
 * @author AC70602
 * @see Cars
 * @see com.ys.cert.model.impl.CarsImpl
 * @see com.ys.cert.model.impl.CarsModelImpl
 * @generated
 */
public interface CarsModel extends BaseModel<Cars>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cars model instance should use the {@link Cars} interface instead.
	 */

	/**
	 * Returns the primary key of this cars.
	 *
	 * @return the primary key of this cars
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cars.
	 *
	 * @param primaryKey the primary key of this cars
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the car ID of this cars.
	 *
	 * @return the car ID of this cars
	 */
	public long getCarId();

	/**
	 * Sets the car ID of this cars.
	 *
	 * @param carId the car ID of this cars
	 */
	public void setCarId(long carId);

	/**
	 * Returns the group ID of this cars.
	 *
	 * @return the group ID of this cars
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this cars.
	 *
	 * @param groupId the group ID of this cars
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this cars.
	 *
	 * @return the company ID of this cars
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this cars.
	 *
	 * @param companyId the company ID of this cars
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this cars.
	 *
	 * @return the user ID of this cars
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this cars.
	 *
	 * @param userId the user ID of this cars
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this cars.
	 *
	 * @return the user uuid of this cars
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this cars.
	 *
	 * @param userUuid the user uuid of this cars
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this cars.
	 *
	 * @return the user name of this cars
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this cars.
	 *
	 * @param userName the user name of this cars
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this cars.
	 *
	 * @return the create date of this cars
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this cars.
	 *
	 * @param createDate the create date of this cars
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this cars.
	 *
	 * @return the modified date of this cars
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this cars.
	 *
	 * @param modifiedDate the modified date of this cars
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the car name of this cars.
	 *
	 * @return the car name of this cars
	 */
	@AutoEscape
	public String getCarName();

	/**
	 * Sets the car name of this cars.
	 *
	 * @param carName the car name of this cars
	 */
	public void setCarName(String carName);

	/**
	 * Returns the car model of this cars.
	 *
	 * @return the car model of this cars
	 */
	@AutoEscape
	public String getCarModel();

	/**
	 * Sets the car model of this cars.
	 *
	 * @param carModel the car model of this cars
	 */
	public void setCarModel(String carModel);

	/**
	 * Returns the car model year of this cars.
	 *
	 * @return the car model year of this cars
	 */
	public int getCarModelYear();

	/**
	 * Sets the car model year of this cars.
	 *
	 * @param carModelYear the car model year of this cars
	 */
	public void setCarModelYear(int carModelYear);

	/**
	 * Returns the car color of this cars.
	 *
	 * @return the car color of this cars
	 */
	@AutoEscape
	public String getCarColor();

	/**
	 * Sets the car color of this cars.
	 *
	 * @param carColor the car color of this cars
	 */
	public void setCarColor(String carColor);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Cars cars);

	public int hashCode();

	public CacheModel<Cars> toCacheModel();

	public Cars toEscapedModel();

	public Cars toUnescapedModel();

	public String toString();

	public String toXmlString();
}